### ISSUE TITLE
Startup crash after adding new irc server

### ISSUE THREAD

**Issue by keredau** [graulund/pyramid#4]
Added a new irc server pointing to my znc with a self signed ssl certificate, added the channels then rebooted pyramid to make it connect to the server. Crashes on startup:

```
/pyramid/node_modules/irc/lib/irc.js:850
                        throw err;
                        ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.getRelationship (/pyramid/server/util.js:212:21)
    at Object.handleIncomingMessage (/pyramid/server/main.js:527:28)
    at handleIncomingMessage (/pyramid/server/irc.js:157:8)
    at Client.<anonymous> (/pyramid/server/irc.js:227:4)
    at emitMany (events.js:127:13)
    at Client.emit (events.js:204:7)
    at Client.<anonymous> (/pyramid/node_modules/irc/lib/irc.js:557:22)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:191:7)
    at iterator (/pyramid/node_modules/irc/lib/irc.js:847:26)
```

**Comment by graulund** [comment]
Try the newest version. I do wonder about messages without usernames, though.
